### ISSUE TITLE
AnimTAB broken with two characters

### ISSUE THREAD

**Issue by HexedHero** [AkiraDevelopment/SimplyMC#50]
Go to https://www.simplymc.art/AnimTAB and put "12" the preview will show it changes between the two colors whereas the copy-paste doesn't do anything at all.

**Comment by Oli-idk** [comment]
ill look into this but like i mean at that point cant you just manually make the animation?

**Comment by saboooor** [comment]
it works just fine wdym

**Comment by Oli-idk** [comment]
> it works just fine wdym

it doesn't, put 2 letters for the text and look at the output it doesn't do anything it's just the same color code and doesn't alternate

**Comment by saboooor** [comment]
ohh nvm then

**Comment by Oli-idk** [comment]
honestly too much work to fix if u cant make a 2 color animation on ur own idk what to tell you
