### ISSUE TITLE
Gradient to text

### ISSUE THREAD

**Issue by assada** [AkiraDevelopment/SimplyMC#71]
Hello. Look some tool for convert gradient string to unformatted string with gradient colors.

Example:
encoded string: `§x§0§0§f§f§e§0T§x§4§e§a§a§e§ae§x§9§d§5§5§f§5s§x§e§b§0§0§f§ft`
decoded string: `test` + gradient start `#00FFE0` and gradient end `#EB00FF`

**Comment by Oli-idk** [comment]
I will attempt this but i cant promise it will work

**Comment by Oli-idk** [comment]
One issue is this would only work for 2 color gradients anything more and it will not work

**Comment by assada** [comment]
gradient color detection is an option. Most useful feature will be decode text.

in my case i forgot what text encoded =)

**Comment by Oli-idk** [comment]
@assada https://www.simplymc.art/MiscTools i have added a gradient decoder to the page, it will basically strip all color codes of the specified type from the string
