### ISSUE TITLE
The output doesn't show anything anymore

### ISSUE THREAD

**Issue by HansOffice** [AkiraDevelopment/SimplyMC#72]
![0XTZOE{}$R_VMOJ2$@X3EJ3](https://user-images.githubusercontent.com/94523696/190674600-5639f79c-6058-4969-b0b3-473c339210d9.png)
I hope to get a reply, using other browsers as well, what happened in the last few days

**Comment by Oli-idk** [comment]
could you press f12 and tell me if there are any errors in the console

**Comment by HansOffice** [comment]
> 您能按 f12 并告诉我控制台中是否有任何错误吗？我 似乎无法重现您的问题 ![图片](https://user-images.githubusercontent.com/67001116/190713700-7507161c-ebcb-48bd-bcc9-81c88b76d216.png)

AnimTab:4 GET https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1579411871326173 net::ERR_CONNECTION_RESET
AnimTABScript.js:216 Uncaught TypeError: animationFormatting.value.replace(...).replace(...).replace(...).replaceAll is not a function
    at updateOutputText (AnimTABScript.js:216)
    at AnimTABScript.js:340
updateOutputText @ AnimTABScript.js:216
(anonymous) @ AnimTABScript.js:340

This is an error report

**Comment by Oli-idk** [comment]
could try clearing your cache and cookies to see if that fixes it

**Comment by HansOffice** [comment]
> 可以尝试清除您的缓存和 cookie 以查看是否可以解决问题

Did not solve

**Comment by Oli-idk** [comment]
what is the value of the "animation formatting" input?

**Comment by HansOffice** [comment]
By default 50, I put the site on edge and it's fine, but all other browsers seem to be such that they can't see the output

> “动画格式”输入的值是多少？

**Comment by Oli-idk** [comment]
what browser are you trying that isn't working

**Comment by HansOffice** [comment]
> 您正在尝试什么浏览器无法正常工作
Twinkstar Browser,A week ago there was no such problem.

**Comment by Oli-idk** [comment]
i have only ever tested it on chromium based browsers and for the best experience i recommend you use one too

**Comment by HansOffice** [comment]
> 我只在基于 chromium 的浏览器上测试过它，为了获得最佳体验，我建议你也使用一个

Ok!Thanks for the answer, thanks for your hard work.

**Comment by Oli-idk** [comment]
no problem
