### ISSUE TITLE
Output does not output text but only color

### ISSUE THREAD

**Issue by HansOffice** [AkiraDevelopment/SimplyMC#73]
Changed many browsers and devices are this problem, no matter what is written in the text will not be output, nor will it take effect
![QQ图片20221209005257](https://user-images.githubusercontent.com/94523696/206514278-cd0e5911-7cc0-4914-bdd8-56b837f84cd5.png)

**Comment by Oli-idk** [comment]
Are there any errors in the console, if so please attach a screenshot of them.

**Comment by HansOffice** [comment]
![Uploading QQ图片20221209012451.png…]()


> 控制台中是否有任何错误，如果有，请附上它们的屏幕截图。

**Comment by HansOffice** [comment]
![QQ图片20221209012451](https://user-images.githubusercontent.com/94523696/206521511-6a103ef0-0682-4626-80c7-bea58ff6ae32.png)
I wasn't able to read this

> 控制台中是否有任何错误，如果有，请附上它们的屏幕截图。

**Comment by Oli-idk** [comment]
that's fine, i think i know the issue and i should be able to fix it in a couple hours.

**Comment by HansOffice** [comment]
> that's fine, i think i know the issue and i should be able to fix it in a couple hours.

Okay, thanks
